[workspace]
[package]
version = "0.1.0"
name = "fibonacci-script"
edition = "2021"

[dependencies]
sp1-sdk = "2.0.0"
hdp = { git = "https://github.com/HerodotusDev/hdp.git", features = [
    "test_utils",
] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
