[workspace]
[package]
version = "0.1.0"
name = "sp1-evm-coprocessor"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
alloy-primitives = "0.6.2"
alloy-dyn-abi = "0.6.2"
